"use client"; // Menandai komponen ini sebagai Client Component

import "./globals.css";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import Navbar from "@/app/components/Navbar/index.js";
import Footer from "@/app/components/Footer/index.js";
import Menus from "@/app/components/Menu/index.js";

const inter = Inter({ subsets: ["latin"] });

// Metadata tidak boleh diekspor dari komponen client
const metadata = {
  title: "KanaeruMyAnimeList",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <div className="flex flex-grow">
            <main className="flex-grow p-4">
              {children} {/* Menampilkan children langsung tanpa delay */}
            </main>
            <Menus className='fixed' />
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
